-- Generated annotated PDFs are separate private objects. The original answer
-- upload remains immutable in answer-uploads.

alter table public.upload_slots
  add column if not exists annotated_object_path text null,
  add column if not exists annotated_generated_at timestamptz null;

comment on column public.upload_slots.annotated_object_path is
  'Private marking-packets object path for the latest generated annotated PDF.';

comment on column public.upload_slots.annotated_generated_at is
  'Time the latest annotated PDF was generated by an owner workflow.';
